### ISSUE TITLE
scripts owrt_client_detail.sh and owrt_client_discover.sh don't appear to be working

### ISSUE THREAD

**Issue by xzyk210957** [Merrick28/zabbix-Openwrt-Clients-monitor#2]
Have Zabbix server running a raspberry pi 4B and it is able to collect data from the openwrt using SNMP, however when i tried your installation I am not getting very far.
When i link the template 'openwrt clients network' zabbix server reports:
Cannot find host interface on "_myhost_" for item key "agent.hostname".
when i execute the scripts above locally on the openwrt client i get:
owrt_client_detail.sh  gives no output.
owrt_client_discover.sh gives error:
{"data":[
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
Executing zabbix_get -s _hostIP_ -k _agent.hostname on server correctly returns the hostname of the client.
Let me know if you need more detail as I'm pretty new to github.
thanks.

**Comment by Merrick28** [comment]
Hello,

it seems you don't have arp installed on your routeur. Can you try
```
opkg update
opk install arptables
```
and tell me if it's ok ?

(I just saw arp is deprecated, so I will try to move to ip neigh in a future release)

**Comment by xzyk210957** [comment]
Hi, thanks for responding. arp-tables is installed but executing the owrt_client_discover.sh still gives error as below:
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
{"{#NETWORK_CLIENT}": "40:8d:5c:ba:f2:bb","{#MACADDR}": "40:8d:5c:ba:f2:bb"}  ....continues listing all MACs
don't see any ips though.

**Comment by Merrick28** [comment]
Did you try to launch the script as root ?
What gives
```
type arp
```
?

**Comment by xzyk210957** [comment]
yes, output below:
andy@WRT3200acm:/etc/zabbix_agentd.conf.d/scripts$ sudo ./owrt_client_discover.sh
{"data":[
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
./owrt_client_discover.sh: line 17: arp: not found
sh: ?$: out of range
{"{#NETWORK_CLIENT}": "40:8d:5c:ba:f2:bb","{#MACADDR}":  ....rest of macs listed not show..

**Comment by xzyk210957** [comment]
I'm getting this with arptables install:
andy@WRT3200acm:/etc/zabbix_agentd.conf.d/scripts$ sudo opkg list | grep arptables
arptables - 2015-05-20-f4ab8f63-1 - ARP firewalling software
kmod-arptables - 5.4.42-1 - Kernel modules for ARP firewalling
andy@WRT3200acm:/etc/zabbix_agentd.conf.d/scripts$ sudo opkg install arptables
Package arptables (2015-05-20-f4ab8f63-1) installed in root is up to date.
andy@WRT3200acm:/etc/zabbix_agentd.conf.d/scripts$ 
so arptables is not installing but kmod-arptables installs fine, don't know if there's a difference..

**Comment by Merrick28** [comment]
Can you give me ?
```
type arp
``` 
?

**Comment by xzyk210957** [comment]
some of them listed below, cannot list all MACs as there's too many...
andy@WRT3200acm:/etc/zabbix_agentd.conf.d/scripts$ arp
IP address       HW type     Flags       HW address            Mask     Device
192.168.50.167   0x1         0x0         48:45:20:b3:8d:5a     *        eth0.50
192.168.50.192   0x1         0x0         00:00:00:00:00:00     *        eth0.50
192.168.50.175   0x1         0x2         dc:a6:32:a1:39:a6     *        eth0.50
192.168.0.178    0x1         0x2         00:24:e8:ba:ea:58     *        br-lan
192.168.50.138   0x1         0x2         20:a6:80:c0:a6:00     *        eth0.50
192.168.50.149   0x1         0x2         06:71:60:07:ef:fd     *        eth0.50
192.168.0.135    0x1         0x0         00:22:4d:88:28:69     *        br-lan

**Comment by Merrick28** [comment]
You misunderstood me, just
```
type arp
```
with the "type" command, il shows the path of the argument, and it will show you where the arp executable is, it should be /sbin/arp.
You can also use
```
which arp
```

**Comment by xzyk210957** [comment]
andy@WRT3200acm:/$ type arp
arp is a function
andy@WRT3200acm:/$ which arp
andy@WRT3200acm:/$

**Comment by xzyk210957** [comment]
andy@WRT3200acm:/$ sudo opkg list-installed | grep arp
arptables - 2015-05-20-f4ab8f63-1
kmod-arptables - 5.4.42-1

**Comment by Merrick28** [comment]
OK, so you don't have the arp binary installed. I just saw that it is part of busybox.
Can you try
```
opkg install busybox
```
?

**Comment by xzyk210957** [comment]
this line of your script works fine:
andy@WRT3200acm:/etc/zabbix_agentd.conf.d/scripts$ sudo /usr/sbin/nlbw -c csv -n -g mac -q|grep -v 00:00:00|tail -n+2
40:8d:5c:ba:f2:bb	494486	194729475932	148768293	7572574498	135557708
78:5d:c8:09:98:dc	55249	66366854141	44368049	952411167	14426990
c0:ee:fb:ec:bb:44	192775	3632248629	4126644	422120613	2921899
06:71:60:07:ef:fd	1119948	1469269074	1713611	108481921	961394
1c:6f:65:3f:41:d9	51710	1456031670	1138026	76225292	722514
etc....

**Comment by xzyk210957** [comment]
andy@WRT3200acm:/etc/zabbix_agentd.conf.d/scripts$ sudo opkg install busybox
Package busybox (1.31.1-1) installed in root is up to date.
seems it was already installed..

**Comment by Merrick28** [comment]
Arg...
we need the arp to join the macadress to the ip adress, so we can resolve the hostname.
Can you please ?
```
ls -al /sbin/arp*
```

**Comment by xzyk210957** [comment]
on my router arp is not in /sbin 
andy@WRT3200acm:/etc/zabbix_agentd.conf.d/scripts$ ls -al /sbin/arp*
ls: /sbin/arp*: No such file or directory
yes, i worked out that's what your script is trying to do, I can get something similar with:
andy@WRT3200acm:/etc/zabbix_agentd.conf.d/scripts$ arp -n
IP address       HW type     Flags       HW address            Mask     Device
192.168.50.167   0x1         0x0         48:45:20:b3:8d:5a     *        eth0.50
192.168.50.192   0x1         0x0         00:00:00:00:00:00     *        eth0.50
192.168.50.175   0x1         0x2         dc:a6:32:a1:39:a6     *        eth0.50
192.168.0.178    0x1         0x2         00:24:e8:ba:ea:58     *        br-lan
192.168.50.138   0x1         0x2         20:a6:80:c0:a6:00     *        eth0.50
192.168.50.149   0x1         0x2         06:71:60:07:ef:fd     *        eth0.50
192.168.0.135    0x1         0x0         00:22:4d:88:28:69     *        br-lan

**Comment by Merrick28** [comment]
That's the point. I don't understand why it works on command line and not in the script ?
The message you gave me
```
./owrt_client_discover.sh: line 17: arp: not found
```
shows that the script is not finding arp, but when you launch manually it works...
I will install a new vm and try to reproduce the issue.

**Comment by xzyk210957** [comment]
ok, thanks, I will continue hunting from my end also..

**Comment by Merrick28** [comment]
If you use only ipv4, I can give you an aolder version that does not use arp

**Comment by xzyk210957** [comment]
you're right, arp is not being found. I entered a quick bash script test:
#!/bin/ash

for ip in $(arp | grep -v IP | awk '{print $1}'); do
    grep $ip /tmp/dhcp.leases;
done
and the result was :+1: 
andy@WRT3200acm:/etc/zabbix_agentd.conf.d/scripts$ ./test.sh
./test.sh: line 3: arp: not found

**Comment by xzyk210957** [comment]
yes please, i disable IPv6 as i don't need it and sometimes gives me more trouble than it's worth..

**Comment by Merrick28** [comment]
Try this : https://github.com/Merrick28/zabbix-Openwrt-Clients-monitor/tree/096ba8afdafe3c9c400872596270e373c25cdb98/scripts
to replace the content of the script directory

**Comment by xzyk210957** [comment]
looks like this one needs 'dig' command as i get:
andy@WRT3200acm:/etc/zabbix_agentd.conf.d/scripts$ ./owrt_client_discover2.sh
{"data":[
./owrt_client_discover2.sh: line 17: dig: not found
trying to install dig gives me:
andy@WRT3200acm:/etc/zabbix_agentd.conf.d/scripts$ sudo opkg install dig
Unknown package 'dig'.
Collected errors:
 * opkg_install_cmd: Cannot install package dig.
is dig called something else ?

**Comment by xzyk210957** [comment]
don't know if it's relevant but have a look at https://dev.archive.openwrt.org/ticket/1203 for arp issue...

**Comment by xzyk210957** [comment]
i installed 'bind-dig':
ndy@WRT3200acm:/etc/zabbix_agentd.conf.d/scripts$ sudo opkg list-installed | grep dig
bind-dig - 9.16.3-1
ddns-scripts_digitalocean.com-v2 - 2.7.8-20
 and now I'm closer..
{"data":[
{"{#NETWORK_CLIENT}": "Wayne-PC.lan.","{#NETWORK_IP}": "192.168.20.137","{#MACADDR}": "40:8d:5c:ba:f2:bb"},{"{#NETWORK_CLIENT}": "192.168.30.167","{#NETWORK_IP}": "192.168.30.167",   etc..
I'm now getting ips from the ipv4 script..

**Comment by xzyk210957** [comment]
unfortunately using the ipv4 script sill gives zabbix server error as show:
![zabbix1](https://user-images.githubusercontent.com/76029230/102229971-3d7d0080-3ee4-11eb-860e-5a4238ed540b.png)

**Comment by Merrick28** [comment]
Stranger and stranger...
On my side, the router has "Template OS Linux" linked, is it possible to try with this template ?

**Comment by Merrick28** [comment]
and I have no "agent.hostname" or wrt* on the template ?

**Comment by xzyk210957** [comment]
other templates give the same error on zabbix, BTW I'm running v5.0
![zabbix2](https://user-images.githubusercontent.com/76029230/102233760-833bc800-3ee8-11eb-9ddc-9a367297c508.png)
looks like zabbix cannot find hostname for this router even though it can discover it via SNMP. I noticed the ipv4 script is supposed to list hostnames but as you can see from above script output no hostname are ever shown.
Anyway, I'll battle on I'm sure it will turn out to be something really simple and stupid...thanks for help so far..

**Comment by Merrick28** [comment]
ah, ok. Your router is auto discovered via snmp. The template I created is for use with zabbix client, I don't know how to merge that.

**Comment by Merrick28** [comment]
As you've installed the agent, you can create a new host on type "zabbix agent" on this server, so you can user other metrics/alerts. The script I provide is only for use with zabbix agent, and cannot work on snmp host type. If you need on that, we can continue by mail, otherwise I will close this issue.

**Comment by xzyk210957** [comment]
let me try and report back..

**Comment by xzyk210957** [comment]
ok, that did it...graphs are now showing, although not yet populated, I guess it'll happen on the next poll.
yes, I'm happy to close it like this..thanks for all your assistance..

**Comment by Merrick28** [comment]
Graphs for owrt clients are not included in the template, but quite easy to do. If you need on that, please request and I will give you the method.
Enjoy your zabbix server :)

**Comment by xzyk210957** [comment]
yes please, that would be great as i run more than one openwrt implementations and some don't have snmpd client loaded on some of them..

**Comment by xzyk210957** [comment]
when i go to add graphs currently the only options i have are:
![zabbix3](https://user-images.githubusercontent.com/76029230/102239888-37405180-3eef-11eb-9291-e156ad5e27b8.png)

**Comment by xzyk210957** [comment]
trying to add this zabbix agent to the discovery check, what do i need for the Key ?

**Comment by Merrick28** [comment]
First of all, you should add the Template OS Linux  to your router, so you can have more infos (disk, cpu, and so on...)

Then to create graph for owrt clients :
Go to config = templates => clic on Openwrt clients network
Go to "discover rules" then "graph prototype" (I don't know the exact word in english)
Create a new graph prototype

On name : Network graph for {#NETWORK_CLIENT}
Elements : On elements, clic on "add prototype", and choose the data you want to show (I suppose upload bytes and download bytes).
Save and the graph should ba available for each client on your router

**Comment by xzyk210957** [comment]
don't have Template OS Linux I have Template OS Linux by Prom, this give only the following options:
![zabbix4](https://user-images.githubusercontent.com/76029230/102244871-c69c3380-3ef4-11eb-890b-c5e122245569.png)
so no interface stats...

**Comment by Merrick28** [comment]
OK, this template is not mandatory, you can add it if you want to monitor cpu and so on.
On "my " template, did you manage to add the graphs ?

**Comment by xzyk210957** [comment]
no configured everything as instructed, graphs displayed but never
populated so i went back to SNMP discovery and everything works fine with
that.
thanks for your support.
