### ISSUE TITLE
Update for 5.4?

### ISSUE THREAD

**Issue by Fl1pp3d0ff** [Merrick28/zabbix-Openwrt-Clients-monitor#4]
This refuses to import into 5.4, and would be useful.
The error messages I'm getting on import are cryptic, at best.
Any chance of an update?

**Comment by Merrick28** [comment]
Hello,
i'm not using this anymore, but I can try to update it. Can you paste me the error message, event if it's cryptic ?

**Comment by Fl1pp3d0ff** [comment]
Looking harder at the error message, it seems there are a boatload of missing SNMPv3 tags.

`Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": the tag "snmpv3_contextname" is missing.`

If that tag gets added (to everywhere there's an snmpv3 block), another missing tag then pops up in the error messages on import.
I'm the first to admit I'm still learning Zabbix and its needs. Version 5.4 is the first version I've installed.

**Comment by johnjamesmarsh** [comment]
I'm using this template with V5.4.3 but with the Agent (not SMNP). There was an issue with the arp command being removed from OpenWRT but I fixed that and have updated the owrt_client_discovery.sh script.

Have you tried the Agent? Or do you need to use SNMPv3?

**Comment by Fl1pp3d0ff** [comment]
> I'm using this template with V5.4.3 but with the Agent (not SMNP). There was an issue with the arp command being removed from OpenWRT but I fixed that and have updated the owrt_client_discovery.sh script.
> 
> Have you tried the Agent? Or do you need to use SNMPv3?

Excuse my curiosity, but how would any of that affect the ability to import the script into Zabbix?  As for the missing OpenWRT commands, that's easily overcome, and I appreciate that heads up.

**Comment by johnjamesmarsh** [comment]
> Excuse my curiosity, but how would any of that affect the ability to import the script into Zabbix? 

Not sure but this is for the Zabbix Agent so there are no SNMP items. Comparing it to my HP Printer template there are it references the SNMP agent. Wouldn't you need a different template with items of type SNMP?

**Comment by Merrick28** [comment]
Hello this project is for use with Zabbix agent, not snmp. It won't work without the zabbix agent. I will update the readme for that

**Comment by Fl1pp3d0ff** [comment]
...yet when trying to import the Zabbix template into Zabbix, Zabbix is asking for SNMPv3 tags.
I suppose I'll need to find another way.
Thanks anyway.

**Comment by Fl1pp3d0ff** [comment]
After re-downloading your XML and making sure Zabbix is fully updated to the latest version, attempting to import your script now gives: 

`Cannot read XML: (41) Specification mandates value for attribute crossorigin [Line: 15 | Column: 76].`

In case you're interested in fixing that... Off to find another solution. Best of luck.

**Comment by johnjamesmarsh** [comment]
Hmm, very strange. All worked fine for me out of the box with Zabbix V5.4.3. Only issue was the the arp deprication.
